// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmnfwpsgisvjxpvccklh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtbmZ3cHNnaXN2anhwdmNja2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzU3ODIsImV4cCI6MjA2NTQxMTc4Mn0._lYkhhjrtTtQd_yuRVMrfVqIppC8g8mopSQ_4lU0tbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);